name: customer_app
description: "My Sanji Customer Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  common:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  otp_text_field: ^1.1.3
  firebase_app_check: ^0.2.1+13
  build_runner: ^2.4.8
  bloc_test: ^9.1.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/india_flag.png
    - assets/images/phone_login_mask.png
    - assets/images/yellowLogo.png
    - assets/images/my_sanji_logo.png


