codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: '80...100'

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - '**/example/'
  - 'examples'
  - '**/*all.dart'
  - '**/*.pb.dart'

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false