# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Melos CI?CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
        - uses: bluefireteam/melos-action@v3
